services:
- type: web
  name: linebot-smart-namecard
  env: go
  buildCommand: go build -o app
  startCommand: ./app
  plan: free
  autoDeploy: false
  envVars:
  - key: ChannelAccessToken
    sync: false
  - key: ChannelSecret
    sync: false
  - key: GOOGLE_GEMINI_API_KEY
    sync: false
  - key: NOTION_INTEGRATION_TOKEN
    sync: false
  - key: NOTION_DB_PAGEID
    sync: false